package hibernate;
// Generated 18-ene-2024 11:41:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private int idDepartamento;
     private String denominacion;
     private Direccion direccion;
     private Empleado jefe;
     private Set empleados = new HashSet(0);

    public Departamento() {
    }
	
    public Departamento(int idDepartamento, Direccion direccion, Empleado jefe, String denominacion) {
        this.idDepartamento = idDepartamento;
        this.direccion = direccion;
        this.jefe = jefe;
        this.denominacion = denominacion;
    }
    public Departamento(int idDepartamento, Direccion direccion, Empleado jefe, String denominacion, Set empleados) {
       this.idDepartamento = idDepartamento;
       this.direccion = direccion;
       this.jefe = jefe;
       this.denominacion = denominacion;
       this.empleados = empleados;
    }

    public int getIdDepartamento() {
        return idDepartamento;
    }

    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    public String getDenominacion() {
        return denominacion;
    }

    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }

    public Direccion getDireccion() {
        return direccion;
    }

    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }

    public Empleado getJefe() {
        return jefe;
    }

    public void setJefe(Empleado jefe) {
        this.jefe = jefe;
    }

    public Set getEmpleados() {
        return empleados;
    }

    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    
}


