package hibernate;
// Generated 18-ene-2024 11:41:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int idEmpleado;
     private String nombre;
     private String apellidos;
     private int salario;
     private Direccion direccion;
     private Departamento departamento;
     private Set tareas = new HashSet(0);
     private Vehiculo vehiculo;
     private Set proyectos;

    public Empleado() {
    }

	
    public Empleado(int idEmpleado, Departamento departamento, Direccion direccion, String nombre, String apellidos, int salario) {
        this.idEmpleado = idEmpleado;
        this.departamento = departamento;
        this.direccion = direccion;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.salario = salario;
    }
    public Empleado(int idEmpleado, Departamento departamento, Direccion direccion, Vehiculo vehiculo, String nombre, String apellidos, int salario, Set tareas, Set proyectos) {
       this.idEmpleado = idEmpleado;
       this.departamento = departamento;
       this.direccion = direccion;
       this.vehiculo = vehiculo;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.salario = salario;
       this.tareas = tareas;
       this.proyectos = proyectos;
    }

    public Set getProyectos() {
        return proyectos;
    }

    public void setProyectos(Set proyectos) {
        this.proyectos = proyectos;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public int getSalario() {
        return this.salario;
    }
    
    public void setSalario(int salario) {
        this.salario = salario;
    }
    public Set getTareas() {
        return this.tareas;
    }
    
    public void setTareas(Set tareas) {
        this.tareas = tareas;
    }


}


