package hibernate;
// Generated 18-ene-2024 11:41:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private String desc;
     private Date fechaInicio;
     private Date fechFin;
     private Empleado responsable;
     private Departamento departamento;

    public Proyecto() {
    }
    
    public Proyecto(int codigo, Empleado empleado, String nombre, String desc, Date fechaInicio, Date fechFin) {
        this.codigo = codigo;
        this.responsable = empleado;
        this.nombre = nombre;
        this.desc = desc;
        this.fechaInicio = fechaInicio;
        this.fechFin = fechFin;
    }

    public int getCodigo() {
        return codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Date getFechaInicio() {
        return fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public Date getFechFin() {
        return fechFin;
    }

    public void setFechFin(Date fechFin) {
        this.fechFin = fechFin;
    }

    public Empleado getResponsable() {
        return responsable;
    }

    public void setResponsable(Empleado responsable) {
        this.responsable = responsable;
    }

    public Departamento getDepartamento() {
        return departamento;
    }

    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    
}


