package hibernate;
// Generated 18-ene-2024 11:41:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private String desc;
     private Date fechaInicio;
     private Date fechFin;
     private Empleado responsable;
     //private Set empleados = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(int codigo, Empleado empleado, String nombre, String desc, Date fechaInicio, Date fechFin) {
        this.codigo = codigo;
        this.responsable = empleado;
        this.nombre = nombre;
        this.desc = desc;
        this.fechaInicio = fechaInicio;
        this.fechFin = fechFin;
    }
    /*public Proyecto(int codigo, Empleado empleado, String nombre, String desc, Date fechaInicio, Date fechFin, Set empleados) {
       this.codigo = codigo;
       this.responsable = empleado;
       this.nombre = nombre;
       this.desc = desc;
       this.fechaInicio = fechaInicio;
       this.fechFin = fechFin;
       this.empleados = empleados;
    }*/
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Empleado getEmpleado() {
        return this.responsable;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.responsable = empleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechFin() {
        return this.fechFin;
    }
    
    public void setFechFin(Date fechFin) {
        this.fechFin = fechFin;
    }
    
    /*
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    */
    
}


