package hibernate;
// Generated 04-mar-2024 12:21:34 by Hibernate Tools 4.3.1


import java.time.LocalDate;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lider generated by hbm2java
 */
public class Lider  implements java.io.Serializable {


     private int idLider;
     private String nombre;
     private LocalDate fechaAlta;

    public Lider() {
    }

    public Lider(String nombre, LocalDate fechaAlta) {
        this.nombre = nombre;
        this.fechaAlta = fechaAlta;
    }
	
    public Lider(int idLider, String nombre, LocalDate fechaAlta) {
        this.idLider = idLider;
        this.nombre = nombre;
        this.fechaAlta = fechaAlta;
    }
   
    public int getIdLider() {
        return this.idLider;
    }
    
    public void setIdLider(int idLider) {
        this.idLider = idLider;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public LocalDate getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(LocalDate fechaAlta) {
        this.fechaAlta = fechaAlta;
    }




}


