package hibernate;
// Generated 04-mar-2024 12:21:34 by Hibernate Tools 4.3.1



/**
 * SeguidoresliderId generated by hbm2java
 */
public class SeguidoresliderId  implements java.io.Serializable {


     private int idLider;
     private int idSeguidor;

    public SeguidoresliderId() {
    }

    public SeguidoresliderId(int idLider, int idSeguidor) {
       this.idLider = idLider;
       this.idSeguidor = idSeguidor;
    }
   
    public int getIdLider() {
        return this.idLider;
    }
    
    public void setIdLider(int idLider) {
        this.idLider = idLider;
    }
    public int getIdSeguidor() {
        return this.idSeguidor;
    }
    
    public void setIdSeguidor(int idSeguidor) {
        this.idSeguidor = idSeguidor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SeguidoresliderId) ) return false;
		 SeguidoresliderId castOther = ( SeguidoresliderId ) other; 
         
		 return (this.getIdLider()==castOther.getIdLider())
 && (this.getIdSeguidor()==castOther.getIdSeguidor());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdLider();
         result = 37 * result + this.getIdSeguidor();
         return result;
   }   


}


