package hibernate;
// Generated 04-mar-2024 12:21:34 by Hibernate Tools 4.3.1


import java.time.LocalDate;
import java.util.Date;

/**
 * Seguidoreslider generated by hbm2java
 */
public class Seguidoreslider  implements java.io.Serializable {


     private SeguidoresliderId id;
     private Lider lider;
     private Seguidor seguidor;
     private LocalDate fechaSeguido;
     private int numMegusta;

    public Seguidoreslider() {
    }

    public Seguidoreslider(SeguidoresliderId id, Lider lider, Seguidor seguidor, LocalDate fechaSeguido, int numMegusta) {
       this.id = id;
       this.lider = lider;
       this.seguidor = seguidor;
       this.fechaSeguido = fechaSeguido;
       this.numMegusta = numMegusta;
    }
   
    public SeguidoresliderId getId() {
        return this.id;
    }
    
    public void setId(SeguidoresliderId id) {
        this.id = id;
    }
    public Lider getLider() {
        return this.lider;
    }
    
    public void setLider(Lider lider) {
        this.lider = lider;
    }
    public Seguidor getSeguidor() {
        return this.seguidor;
    }
    
    public void setSeguidor(Seguidor seguidor) {
        this.seguidor = seguidor;
    }
    public LocalDate getFechaSeguido() {
        return this.fechaSeguido;
    }
    
    public void setFechaSeguido(LocalDate fechaSeguido) {
        this.fechaSeguido = fechaSeguido;
    }
    public int getMegusta() {
        return numMegusta;
    }
    
    public void setMegusta(int megusta) {
        this.numMegusta = megusta;
    }




}


