package hibernate;
// Generated 04-mar-2024 12:21:34 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Seguidor generated by hbm2java
 */
public class Seguidor implements java.io.Serializable {

  private int idSeguidor;
  private String nick;
  private String correo;
  private String pais;
  private Set lideresSeguidos = new HashSet(0);

  public Seguidor() {
  }
  
  public Seguidor(String nick, String correo, String pais) {
    this.idSeguidor = idSeguidor;
    this.nick = nick;
    this.correo = correo;
    this.pais = pais;
  }

  public Seguidor(int idSeguidor, String nick, String correo, String pais) {
    this.idSeguidor = idSeguidor;
    this.nick = nick;
    this.correo = correo;
    this.pais = pais;
  }

  public Seguidor(int idSeguidor, String nick, String correo, String pais, Set lideresSeguidos) {
    this.idSeguidor = idSeguidor;
    this.nick = nick;
    this.correo = correo;
    this.pais = pais;
    this.lideresSeguidos = lideresSeguidos;
  }

  public int getIdSeguidor() {
    return this.idSeguidor;
  }

  public void setIdSeguidor(int idSeguidor) {
    this.idSeguidor = idSeguidor;
  }

  public String getNick() {
    return this.nick;
  }

  public void setNick(String nick) {
    this.nick = nick;
  }

  public String getCorreo() {
    return this.correo;
  }

  public void setCorreo(String correo) {
    this.correo = correo;
  }

  public String getPais() {
    return this.pais;
  }

  public void setPais(String pais) {
    this.pais = pais;
  }

  public Set getLideresSeguidos() {
    return this.lideresSeguidos;
  }

  public void setLideresSeguidos(Set lideresSeguidos) {
    this.lideresSeguidos = lideresSeguidos;
  }

}
