package hibernate;
// Generated 05-feb-2024 13:22:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int numCliente;
     private String nombre;

    public Cliente() {
    }

	
    public Cliente(int numCliente, String nombre) {
        this.numCliente = numCliente;
        this.nombre = nombre;
    }
   
    public int getNumCliente() {
        return this.numCliente;
    }
    
    public void setNumCliente(int numCliente) {
        this.numCliente = numCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

}


