package hibernate;
// Generated 05-feb-2024 13:22:21 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reparacion generated by hbm2java
 */
public class Reparacion  implements java.io.Serializable {


    private String codigo;
    private Date fecha;
    private Double precio;

    public Reparacion() {
    }

	
    public Reparacion(String codigo, Date fecha) {
        this.codigo = codigo;
        this.fecha = fecha;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }




}


