package hibernate;
// Generated 05-feb-2024 13:22:21 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private String matricula;
     private Cliente propietario;
     private String marca;
     private String modelo;
     private Set reparaciones = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(String matricula, Cliente cliente, String marca, String modelo) {
        this.matricula = matricula;
        this.propietario = cliente;
        this.marca = marca;
        this.modelo = modelo;
    }
    public Vehiculo(String matricula, Cliente cliente, String marca, String modelo, Set reparacions) {
       this.matricula = matricula;
       this.propietario = cliente;
       this.marca = marca;
       this.modelo = modelo;
       this.reparaciones = reparacions;
    }
   
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public Cliente getPropietario() {
        return this.propietario;
    }
    
    public void setPropietario(Cliente cliente) {
        this.propietario = cliente;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Set<Reparacion> getReparaciones() {
        return this.reparaciones;
    }
    
    public void setReparaciones(Set reparaciones) {
        this.reparaciones = reparaciones;
    }




}


